### ISSUE TITLE
[ARM]: Setup arm subsystem

### ISSUE THREAD

**Issue by Gitter499** [RoboLancers/321-havoc-2023#1]
- Absolute Encoders
- Motors
- Setup PID Controller (w/ voltage, current, compensation, soft-limits)
- Setup constants

**Comment by AT727** [comment]
done
made dev-arm-1 branch on my fork
pull request from that branch to dev branch on main repo

*Might have to change from Rev Absolute encoder to WPILIB Analog Encoder class*
